# Generated by Django 5.1.5 on 2025-01-27 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_book_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
    ]
