# Generated by Django 5.1.5 on 2025-02-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_book_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.IntegerField(default=0),
        ),
    ]
