# Generated by Django 5.1.5 on 2025-02-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_delete_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a book genre (e.g. Science Fiction, French Poetry etc.)', max_length=200)),
            ],
        ),
    ]
