# Generated by Django 5.1.5 on 2025-02-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_remove_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.TextField(help_text='Select a genre for this book', null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(default='Drama', help_text='Enter a book genre (e.g. Science Fiction, French Poetry etc.)', max_length=200),
        ),
    ]
