# Generated by Django 5.1.5 on 2025-02-03 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_book_genre_alter_genre_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='book',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='book',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='student',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='student',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Borrower',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
